### ISSUE TITLE
Дополнения о проверке рута

### ISSUE THREAD

**Issue by LuigiVampa92** [Android-Guards/faq#1]
Для проверки рута из натива есть неплохая и удобно дописываемая либа:
https://github.com/DimaKoz/meat-grinder

У неё даже есть демо приложение в маркете:
https://play.google.com/store/apps/details?id=com.kozhevin.rootchecks

Но magiskhide она пробить всё равно не может, зато может выявить более примитивные велосипеды пытающиеся спрятать рут, или инструменты хукающие из андроид рантайма, например xposed

==============

От этого же автора есть не менее годная либа проверяющая подпись приложения не через андроид фреймворк, а из натива, полезно в тех же случаях:
https://github.com/DimaKoz/stunning-signature

**Comment by Fi5t** [comment]
Про проверку подписи чуть позже добавлю отдельный вопрос и тогда внесу туда эту инфу.
